name: AGBS
main: net.AllGamer.AGBS.AGBS
version: 0.1
commands:
    aban:
        description: Ban a user with AGBS
        usage: |
               /<command> [target] [reason flags]
    abanip:
        description: Ban a user's IP with AGBS
        usage: |
               /<command> [target] [reason flags]
    check:
        description: check a user against the AGBS API
        usage: |
               /<command> [target]
    unban:
        description: unban a user locally and against the AGBS api
        usage: |
               /<command> [target]
    exempt:
        description: exempt a user from ban checks
        usage: |
               /<command> [target]