name:AGBS

main:AllGamer.AGBS.AGBS

version:0.1

commands:
    aban:
        description: Ban a user with AGBS
        usage: |
               /<command> [target] [reason flags]
    abanip:
        description: Ban a user's IP with AGBS
        usage: |
               /<command> [target] [reason flags]