name: Bans
main: net.craftrepo.Bans.Bans
version: 0.1
commands:
    aban:
        description: Ban a user with Bans API
        usage: |
               /<command> [target] [reason flags]
    abanip:
        description: Ban a user's IP with the Bans API
        usage: |
               /<command> [target] [reason flags]
    acheck:
        description: Check a user against the Bans API
        usage: |
               /<command> [target]
    aunban:
        description: Unban a user locally and against the Bans API
        usage: |
               /<command> [target]
    aexempt:
        description: Exempt a user from ban checks
        usage: |
               /<command> [target]
    aunbanip:
        description: Unban a user's IP address
        usage: |
               /<command> [target]